const anime = [
  {
    artist: "",
    title: "Warrior",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "AOT",
    style: ["Anime OST"],
    cover: "img/AOT - Warrior.jpg"
  },
  {
    artist: "",
    title: "Prologue",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "DBZ",
    style: ["Anime OST"],
    cover: "img/DBZ - Prologue.jpg"
  },
  {
    artist: "",
    title: "Brothers",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "FMA",
    style: ["Anime OST"],
    cover: "img/FMA - Brothers.jpg"
  },
  {
    artist: "",
    title: "Kamado Tanjiro no Uta",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "KNY",
    style: ["Anime OST"],
    cover: "img/KNY - Kamado Tanjiro no Uta.jpg"
  },
  {
    artist: "",
    title: "Main Theme",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "Naruto",
    style: ["Anime OST"],
    cover: "img/Naruto - Main Theme.jpg"
  },
  {
    artist: "",
    title: "Bink's Sake",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "One Piece",
    style: ["Anime OST"],
    cover: "img/One Piece - Bink's Sake.jpg"
  },
  {
    artist: "",
    title: "Journey To The West",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "Mononoke",
    style: ["Anime OST"],
    cover: "img/Mononoke - Journey To The West.jpg"
  }
];
