const anime = [
  {
    artist: "",
    title: "Warrior",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "AOT",
    style: ["Anime OST"],
    cover: "img/AOT.jpg"
  },
  {
    artist: "",
    title: "Prologue",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "DBZ",
    style: ["Anime OST"],
    cover: "img/DBZ.jpg"
  },
  {
    artist: "",
    title: "Brothers",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "FMA",
    style: ["Anime OST"],
    cover: "img/FMA.jpg"
  },
  {
    artist: "",
    title: "Kamado Tanjiro no Uta",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "KNY",
    style: ["Anime OST"],
    cover: "img/Demon Slayer.jpg"
  },
  {
    artist: "",
    title: "Main Theme",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "Naruto",
    style: ["Anime OST"],
    cover: "img/Naruto.jpg"
  },
  {
    artist: "",
    title: "Bink's Sake",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "One Piece",
    style: ["Anime OST"],
    cover: "img/One Piece.jpg"
  },
  {
    artist: "",
    title: "Journey To The West",
    duration: "",
    year: "",
    category: "",
    mediaType: "Anime",
    gameUniverse: "",
    finalFantasy: "",
    license: "Mononoke",
    style: ["Anime OST"],
    cover: "img/Mononoke.jpg"
  }
];
